clone_depth: 1
version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Debug
install:
  - cmd: git submodule update --init --recursive
  - cmd: choco install resharper-clt -y
  - cmd: choco install nvika -y
  - cmd: appveyor DownloadFile https://github.com/peppy/CodeFileSanity/releases/download/v0.2.5/CodeFileSanity.exe
before_build:
  - cmd: CodeFileSanity.exe
  - cmd: nuget restore
environment:
  TargetFramework: net471
build:
  project: osu-framework.sln
  parallel: true
  verbosity: minimal
test_script:
  # temporary until we switch to dotnet. avoids duplicate test runs.
  - nunit3-console "osu.Framework.Tests\bin\Debug\net471\osu.Framework.Tests.exe" --result=myresults.xml;format=AppVeyor
after_build:
  - cmd: inspectcode /o="inspectcodereport.xml" /caches-home="inspectcode" osu-framework.sln
  - cmd: NVika parsereport "inspectcodereport.xml" --treatwarningsaserrors
  - cmd: dotnet pack osu.Framework --include-symbols /p:Version=0.0.%APPVEYOR_BUILD_VERSION%
artifacts:
  - path: osu.Framework/bin/Debug/*.nupkg

  